
## **Array Operations**

NumPy allows **element-wise** operations, making array manipulations straightforward.

### **1. Arithmetic Operations**
Operate on arrays element-wise. Arrays must have the same shape, or be broadcastable.

#### Examples:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#Addition
#Subtraction
#Multiplication
#Division
#Modular division
#True division


#### **Broadcasting**
When arrays of different shapes interact, NumPy stretches the smaller array to match the larger one if compatible.

arr1 = np.array([1, 2, 3])
print(arr1 + 10)  
print(arr1 - 10)
print(arr1 *10)
print(arr1 / 10)
print(arr1 % 10)
print(arr1 // 10)



#### Examples:

arr = np.array([True, False, True])

#Logical NOT
print(~arr)  # Output: [False  True False]

#Logical AND
print(arr & np.array([False, False, True]))  # Output: [False False  True]

#Logical OR
print(arr | np.array([False, True, False]))  # Output: [ True  True  True]

### **3. Comparison Operations**
Compare elements element-wise. Outputs a boolean array.

#### Examples:
arr1 = np.array([10, 20, 30])
arr2 = np.array([20, 20, 10])

 Element-wise comparison
print(arr1 > arr2)  # Output: [False False  True]
print(arr1 == arr2) # Output: [False  True False]

### **4. Aggregate Operations**
Perform calculations on all elements of an array.

#### Examples:
arr = np.array([1, 2, 3, 4, 5])

#Sum
print(arr.sum())  
#Mean
print(arr.mean()) 
#Max
print(arr.max())  


### **Summary**
| **Operation**      | **Description**                                             |
|---------------------|-------------------------------------------------------------|
| Indexing           | Access elements using indices.                              |
| Slicing            | Extract portions of arrays using `start:stop:step`.         |
| Arithmetic         | Perform element-wise operations (`+`, `-`, `*`, `/`).       |
| Logical            | Perform element-wise logical operations (`&`, `|`, `~`).    |
| Comparison         | Compare arrays element-wise (`>`, `<`, `==`).               |
| Aggregate          | Compute sum, mean, max, etc., over the array.               |

Let me know if you'd like specific examples for complex operations or further explanation!

In [ ]:
import numpy as np

#### Arithmatic Operations:

In [3]:
import numpy as np

In [1]:
x= 23
y=34
print(x+y)

57


In [3]:
A1 = np.array([1,2,3])
A2 = np.array([5,6,7])
print(A1+A2)

[ 6  8 10]


In [4]:
A1 = np.array([1,2,3])
A2 = np.array([5,6,7])
print(A1-A2)

[-4 -4 -4]


In [5]:
A1 = np.array([1,2,3])
A2 = np.array([5,6,7])
print(A1*A2)

[ 5 12 21]


In [6]:
A1 = np.array([5,10,15])
A2 = np.array([5,5,5])
print(A1/A2)

[1. 2. 3.]


In [8]:
A1 = np.array([5,10,15])
A2 = np.array([5,5,5])
print(A1%A2)

[0 0 0]


In [7]:
A1 = np.array([5,10,15])
A2 = np.array([5,5,5])
print(A1//A2)

[1 2 3]


#### BroadCasting:

In [9]:
array_1 = np.array([2,3,4])
print(array_1 + 10)

[12 13 14]


In [10]:
array_1 = np.array([2,3,4])
print(array_1 -1)

[1 2 3]


In [11]:
array_1 = np.array([2,3,4])
print(array_1 *10)

[20 30 40]


In [12]:
array_1 = np.array([2,6,4])
print(array_1/2)

[1. 3. 2.]


In [13]:
array_1 = np.array([2,6,4])
print(array_1%2)

[0 0 0]


In [14]:
array_1 = np.array([2,6,4])
print(array_1//2)

[1 3 2]


### **2. Logical Operations**
Element-wise logical operations are applied to arrays.


In [15]:
array2 = np.array([True,False])
print(~array2)

[False  True]


In [16]:
array11 = np.array([True,False])
array12 = np.array([True,False])
print(array11&array12)

[ True False]


In [4]:
array11 = np.array([True,False,True,False])
array12 = np.array([True,False,False,False])
print(array11&array12)

[ True False False False]


In [17]:
array11 = np.array([True,False])
array12 = np.array([True,False])
print(array11 | array12)

[ True False]


In [ ]:
array11 = np.array([True,False,True,False])
array12 = np.array([True,False,False,False])
print(array11|array12)

### **3. Comparison Operations**
Compare elements element-wise. Outputs a boolean array.


In [6]:
import numpy as np

In [7]:

#### Examples: 
arr1 = np.array([10, 20, 30])
arr2 = np.array([20, 20, 10])

# Element-wise comparison
print(arr1 > arr2)
print(arr1 < arr2) 
print(arr1 >= arr2) 
print(arr1 <= arr2) 
print(arr1 == arr2) 

[False False  True]
[ True False False]
[False  True  True]
[ True  True False]
[False  True False]


### **4. Aggregate Operations**
Perform calculations on all elements of an array.


In [ ]:
import numpy as np

In [ ]:

#### Examples:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())  
print(arr.mean()) 
print(arr.max())  
print(arr.min())
print(np.median(arr))


In [3]:
import numpy as np

In [4]:
array = np.array([24,45,65,76,21])
print(array.sum())

231


In [7]:
array = np.array([24,45,65,76,21])
print(array.mean())

46.2


In [8]:
array = np.array([24,45,65,76,21])
print(array.min())

21


In [9]:
array = np.array([24,45,65,76,21])
print(array.max())

76


## **Array Indexing and Slicing**

### **1. Indexing**
Indexing is the process of accessing individual elements of an array


#### **1D Array**
- A one-dimensional array acts like a list.
- Use square brackets `[]` to access elements.


In [11]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])  
print(arr[-1]) #(negative index)

30
50


In [14]:
name = ["Rohini","sayli","Afnan","utkarsh","Suresh"]
name_array = np.array(name)
print(name_array)
print(name_array[2])
print(name_array[1],name_array[2])



['Rohini' 'sayli' 'Afnan' 'utkarsh' 'Suresh']
Afnan
sayli Afnan


#slicing in array

In [15]:
name = ["Rohini","sayli","Afnan","utkarsh","Suresh"]
slicing_array = np.array(name)
print(slicing_array[1:4])

['sayli' 'Afnan' 'utkarsh']


In [20]:
number_array = [1,2,3,4,5,6] # o/p 2,4
slice_array = np.array(number_array)
print(slice_array)
print(slice_array[::2])
print(slice_array[::-1])
print(slice_array[1:5:2])
print(slice_array[1:4:2])
print(slice_array[1:4:2])

                      

[1 2 3 4 5 6]
[1 3 5]
[6 5 4 3 2 1]
[2 4]
[2 4 6]
[2 4]


#### **2D Array**
- Use two indices: `arr[row, column]`.


In [21]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#print(arr2d) 
print(arr2d[1, 2]) 


6


In [23]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d) 
print(arr2d[2, 2]) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


### **2. Slicing**
Slicing extracts a portion of an array. The syntax is:
```python
array[start:stop:step]
```






In [26]:
#### **1D Array**
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    
#print(arr[:3])     
print(arr[::2])   


[20 30 40]
[10 20 30]
[10 30 50]


In [25]:
#### **2D Array**
#- Slice rows and columns individually.

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[1: , :2])  # Output: [[4 5] [7 8]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[1: ])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[0:3 , :2])

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1: , :2])  # Output: [[4 5] [7 8]]

[[4 5 6]
 [7 8 9]]


In [28]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subarray = arr2d[0:2, 1:3]
print(arr2d)
print(subarray)
#2,3,5,6
#2,3,5,6
#1,2,3,4,5,6

In [44]:
array2 = [[23,43,56,43],[34,65,76,87],[43,54,65,76],[43,32,21,43]]
array3 = np.array(array2)
print(array3)
#o/p 
#76,87
#65,76
#21,43
print(array3[1:4,2:4])
print(array3[1:4,4:1:-1])


[[23 43 56 43]
 [34 65 76 87]
 [43 54 65 76]
 [43 32 21 43]]
[[76 87]
 [65 76]
 [21 43]]
[[87 76]
 [76 65]
 [43 21]]
