### Introduction to NumPy in Python

NumPy, short for **Numerical Python**, is a powerful library in Python used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them. It is widely used in data analysis, machine learning, and scientific computing due to its performance and ease of use.

---


### Installation:
To install NumPy, use the following command in your terminal or command prompt:

pip install numpy




### Basic Operations in NumPy:
Here are some fundamental aspects of using NumPy:

#### 1. **Importing NumPy**

import numpy as np


#### 2. **Creating Arrays**

#1.Creating a 1D array
array_1d = np.array([1, 2, 3])

 #2.Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])




#### 4.Special Arrays:

1.Zeros: np.zeros((2, 3))

Ones: np.ones((3, 3))

Identity Matrix: np.eye(3)

Range: np.arange(0, 10, 2)

Random: np.random.rand(3, 3)

### Why Use NumPy?
- **Performance**: Operations on NumPy arrays are significantly faster than on Python lists due to optimized C implementations.
- **Memory Efficiency**: NumPy arrays use less memory compared to lists.
- **Ease of Use**: Simplifies complex mathematical operations with a concise syntax.

In [ ]:
import numpy as np
array_1d = np.array([1, 2, 3])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Creating an array of zeros
zeros = np.zeros((3, 3))

# Creating an array of ones
ones = np.ones((2, 4))

# Creating an array with a range of values
range_array = np.arange(0, 10, 2)

# Creating an evenly spaced array
linspace_array = np.linspace(0, 1, 5)


In [1]:
import numpy as np

#### 1D Array :

In [2]:
array_1d = np.array([1, 2, 3])
print(array_1d)

[1 2 3]


In [7]:
new_array=np.array([1,2,3,4.5])
print(new_array)

[1.  2.  3.  4.5]


In [3]:
list1 = [1,2,3.4,5.4,'c']
list1

[1, 2, 3.4, 5.4, 'c']

In [4]:
array_1d = np.array([1, 2,  3,"y",4.5])
print(array_1d)

['1' '2' '3' 'y' '4.5']


In [ ]:
array = np.array([1,2,3,4,5])
print(array)

In [ ]:
list1 = [1,2,3,4,5]
array = np.array(list1)
print(array)

In [6]:
array_1d = np.array([1, 2,  3,4.5])
print(array_1d)
print(type(array_1d))

[1.  2.  3.  4.5]
<class 'numpy.ndarray'>


#### 2D Array :

In [14]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [17]:
list2 = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list2)
print(array_2d)


[[1 2 3]
 [4 5 6]]


#### 3. MultiDimentional Array

In [19]:
list1 = [[1,2],[3,4],[5,6]]
array = np.array(list1)
print(array)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
range_array = np.arange(0, 11)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#4.Special Arrays:

Zeros: np.zeros((2, 3))

Ones: np.ones((3, 3))

Identity Matrix: np.eye(3)

Range: np.arange(0, 10, 2)

Random: np.random.rand(3, 3)

In [23]:
Identity =np.eye(3,dtype = int)
print(Identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [21]:
#Random=np.random.rand(3, 3)
random_integers = np.random.randint(10, 20, (2, 3))
print(random_integers)

[[18 15 16]
 [19 13 15]]


In [1]:
import numpy as np

In [4]:
zeros = np.zeros((2,3) ,dtype = int)
print(zeros)

[[0 0 0]
 [0 0 0]]


In [6]:
zero_array = np.zeros((3,3) ,dtype=int)
print(zero_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
one_array = np.ones((2,4),dtype = int)
print(one_array)

[[1 1 1 1]
 [1 1 1 1]]


In [14]:
one_array1= np.ones((4,5),dtype = int)
print(one_array1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
Identity_Matrix = np.eye(3)
print(Identity_Matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
range_array = np.arange(0, 11, 2)
print(range_array)

[ 0  2  4  6  8 10]


In [18]:
Random = np.random.rand(3, 3)
print(Random)

[[0.58718171 0.48872856 0.02531603]
 [0.69345797 0.07985233 0.82216139]
 [0.26268324 0.478201   0.53045836]]


In [ ]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)