In [ ]:





#### **1.3 
- **Example:**
  ```python
  arr = np.array([[1, 2], [3, 4], [5, 6]])
  transposed = arr.T
  print(transposed)
  # Output:
  # [[1 3 5]
  #  [2 4 6]]
  ```

#### **1.4 
- **Example:**
  ```python
  arr1 = np.array([1, 2])
  arr2 = np.array([3, 4])
  combined = np.concatenate((arr1, arr2))
  print(combined)  # Output: [1 2 3 4]
  ```

---


- **Example:**
  ```python
  arr = np.array([10, 20, 30])
  mean = np.mean(arr)
# print(arr.mean())
  print(mean)  # Output: 20.0
  ```

#### **2.2 Median**
- **Purpose:** Finds the middle value in a sorted array.
- **Example:**
  ```python
  arr = np.array([10, 30, 20])
  median = np.median(arr)
  print(median)  # Output: 20.0
  ```

#### **2.3 Standard Deviation (std)**
- **Purpose:** Measures the spread of data from the mean.
- **Example:**
  ```python
  # Output: 8.16496580927726
  ```

#### **2.4 Variance (var)**
- **Purpose:** Measures the average squared deviation from the mean.
- **Example:**
  ```python
  arr = np.array([10, 20, 30])
  variance = np.var(arr)
  print(variance)  



### **Combining Both:**
Here’s an example that includes both array manipulation and statistical operations:
```python
import numpy as np

# Create a 1D array
arr = np.arange(1, 13)  # [1, 2, ..., 12]

# Reshape it to 3x4
reshaped = arr.reshape(3, 4)


 [ 9 10 11 12]]
Mean: 6.5, Median: 6.5, Std Dev: 3.452052529534663, Variance: 11.916666666666666
```


## Common Functions for Array Manipulation**
#### 1.Reshape : Changes the shape of an array without changing its data.
#### 2.Revel :Flattens a multi-dimensional array into a 1D array.
#### 3.Transpose :Flips the dimensions of an array (rows become columns, and vice versa).
#### 4.Concatenate :Joins arrays along an existing axis.

In [2]:
import numpy as np
arr_orignal = np.arange(6)  # [0, 1, 2, 3, 4, 5]
reshaped = arr.reshape(2, 3)  # Reshape to 2 rows and 3 columns
print(arr_orignal)
print(reshaped)

 

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr.ravel()
print(arr)
print(flat)  # Output: [1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [5]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
transposed = arr.T
print(arr)
print(transposed)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [6]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
combined = np.concatenate((arr1, arr2))
print(combined) 

[1 2 3 4]


In [7]:
arr = np.array([10, 20, 30])
mean = np.mean(arr)
print(mean) 

20.0


In [8]:
arr = np.array([10, 20, 30])
mean = np.mean(arr)
print(arr.mean())
print(mean)  # Output: 20.0
 


20.0
20.0


In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30])
std_dev = np.std(arr)
print(std_dev)  

8.16496580927726


In [4]:
arr = np.array([10, 20, 30])
std_dev = np.var(arr)
print(std_dev)  

66.66666666666667
